---
sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule==2.22rc1 
  - pip install flake8
  - pip install cerberus==1.3.1
  - pip install docker
script:
  # TODO re-enable the simple test after we merged the molecule lint fix PR
  # - molecule test
  - molecule test --scenario-name kdc-with-replica

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
